name: Create Artifact
description: "Create Artifact from the output of the jobs"
inputs:
  filename:
    required: true
    type: string
  path:
    required: true
    type: string

runs:
  using: composite
  steps:
    - uses: actions/upload-artifact@v3
      with:
        name: ${{inputs.filename}}
        path: ${{inputs.path}}
          
