name: Create Build
on:
    workflow_call:
    workflow_dispatch:

jobs:
    Test:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: ./react-webapp/
        steps:
            - uses: NaitikPandya/actions-learn@main
            - name: 'Create a Build'
              run: npm run build
            - name: 'Create a Zip File'
              run: zip -r todo.zip build/
            - name: Upload Build
              uses: actions/upload-artifact@v3
              with:
                  name: Build
                  path: ${{github.workspace}}/react-webapp/todo.zip
